version: "3"

services:
    db:
        image: postgres:12.2
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: auth
        ports:
            - "5432:5432"
    api:
      build: .
      depends_on:
        - db
      ports:
        - "3000:3000"
      environment:
          POSTGRES_URL: "postgres://postgres:postgres@db:5432/auth?sslmode=disable"
          PORT: 3000
          JWT_SECRET: "my-super-secret"
