version: "3.8"

services:
    db:
        image: postgres:12.2
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: auth
        ports:
            - 5432:5432
